// Mocks generated by Mockito 5.0.15 from annotations
// in kingpinssdp/test/login_function_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;
import 'dart:convert' as _i6;
import 'package:http/http.dart' as http;
import 'package:http/src/client.dart' as _i4;
import 'package:http/src/response.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

class Res{
  static Future<http.Response> res = Future<http.Response>.value(http.Response('{"email":"thapelo@wits.ac.za","firstname":"Thapelo","lastname":"Mafiri","funds":"35750.00","image":"yes"}',200));
}
/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i4.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i6.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Res.res, returnValueForMissingStub: Res.res)
          as _i5.Future<_i2.Response>);
}
